version: '3'
services:
  mlflow-server:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:8282
    volumes:
      - ./mlruns:/mlflow/mlflow-artifacts
  app:
    build: ./app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:8282
    depends_on:
      - mlflow-server
    ports:
      - "5000:5000"
